title: "Yo, yo mismo y Linux"
author: "Albert"
#description: "Hecho con <b style=\"color: #f45;\">&lt;3</b>"
description: "Mi nombre es Albert y este blog personal es para publicar cosas de Linux y Android entre otras cosas mas que se me ocurran."
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "post.html"}
  - {title: Emulador, icon: game-console-handheld, file: "emulador.md"}
  - {title: Sobre, icon: user, file: "README.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: E-Mail, icon: envelope, url: "mailto:albert.esparrell@disroot.org"}
  - {title: Github, icon: github, url: "https://github.com/LoneWolf93"}
  - {title: RSS, icon: rss, url: "/feed.xml"}
  - {title: Mastodon, icon: mastodon, url: "https://social.linux.pizza/@CondeChocula"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
